# ---------------------------------------------------------------------------------------
#   GCP ‚Ä∫ Update keeweb.info Website
#   Pushes a new version of the Keeweb.info website to Google Cloud Platform
# ---------------------------------------------------------------------------------------

run-name: "üá¨ GCP ‚Ä∫ Deploy ‚Ä∫ KeeWeb.info"
name: "üá¨ GCP ‚Ä∫ KeeWeb.info"

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:

      - name: "‚úÖ Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "‚òÅÔ∏è Setup GCloud"
        uses: google-github-actions/setup-gcloud@v0.7.0
        with:
          version: '285.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: "‚Ü©Ô∏è Restore git mtime"
        run: curl -Ss https://raw.githubusercontent.com/MestreLion/git-tools/f3cc70b73200154d027554714c354f35a08680ed/git-restore-mtime | python3

      - name: "üîÉ Sync"
        run: gsutil -m rsync -r -d -x "^\.|^[a-f\d-]{36}$|^README\.md$" . gs://keeweb.info/

      - name: "üßπ Purge CloudFlare cache"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_TOKEN }}
        run: |
          curl -sS -X POST "https://api.cloudflare.com/client/v4/zones/dbda8e7e454d23edb08d4bc3b3f6f872/purge_cache" \
            -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
